enum CimRecordClass {
    MicrosoftDNS_AAAAType  = 28       # Represents an IPv6 Address (AAAA) often pronounced quad-A RR
    MicrosoftDNS_AFSDBType = 18       # Represents an Andrew File System Database Server (AFSDB) RR
    MicrosoftDNS_ATMAType  = 34       # Represents an ATM Address-to-Name (ATMA) RR.
    MicrosoftDNS_AType     = 1        # Represents an Address (A) RR
    MicrosoftDNS_CNAMEType = 5        # Represents a Canonical Name (CNAME) RR
    MicrosoftDNS_HINFOType = 13       # Represents a Host Information (HINFO) RR
    MicrosoftDNS_ISDNType  = 20       # Represents an ISDN RR
    MicrosoftDNS_KEYType   = 25       # Represents a KEY RR
    MicrosoftDNS_MBType	   = 7        # Represents a Mailbox (MB) RR
    MicrosoftDNS_MDType	   = 3        # Represents a Mail Agent for Domain (MD) RR
    MicrosoftDNS_MFType	   = 4        # Represents a Mail Forwarding Agent for Domain (MF) RR
    MicrosoftDNS_MGType    = 8        # Represents an MG RR
    MicrosoftDNS_MINFOType = 14       # Represents an Mail Information (MINFO) RR
    MicrosoftDNS_MRType    = 9        # Represents a Mailbox Rename (MR) RR
    MicrosoftDNS_MXType    = 15       # Represents a Mail Exchanger (MX) RR
    MicrosoftDNS_NSType	   = 2        # Represents a Name Server (NS) RR
    MicrosoftDNS_NXTType   = 30       # Represents a Next (NXT) RR
    MicrosoftDNS_PTRType   = 12       # Represents a Pointer (PTR) RR
    MicrosoftDNS_RPType    = 17       # Represents a Responsible Person (RP) RR
    MicrosoftDNS_RTType    = 21       # Represents a Route Through (RT) RR
    MicrosoftDNS_SIGType   = 24       # Represents a Signature (SIG) RR
    MicrosoftDNS_SOAType   = 6        # Represents a Start Of Authority (SOA) RR
    MicrosoftDNS_SRVType   = 33       # Represents a Service (SRV) RR
    MicrosoftDNS_TXTType   = 16       # Represents a Text (TXT) RR
    MicrosoftDNS_WINSType  = 65281    # Represents a WINS RR
    MicrosoftDNS_WINSRType = 65282    # Represents a WINS-Reverse (WINSR) RR
    MicrosoftDNS_WKSType   = 11       # Represents a Well-Known Service (WKS) RR
    MicrosoftDNS_X25Type   = 19       # Represents an X.25 (X25) RR
}