enum RCode {
    NoError  = 0     # No Error                                    [RFC1035]
    FormErr  = 1     # Format Error                                [RFC1035]
    ServFail = 2     # Server Failure                              [RFC1035]
    NXDomain = 3     # Non-Existent Domain                         [RFC1035]
    NotImp   = 4     # Not Implemented                             [RFC1035]
    Refused  = 5     # Query Refused                               [RFC1035]
    YXDomain = 6     # Name Exists when it should not              [RFC2136]
    YXRRSet  = 7     # RR Set Exists when it should not            [RFC2136]
    NXRRSet  = 8     # RR Set that should exist does not           [RFC2136]
    NotAuth  = 9     # Server Not Authoritative for zone           [RFC2136]
    NotZone  = 10    # Name not contained in zone                  [RFC2136]
    BadVers  = 16    # Bad OPT Version                             [RFC2671]
    BadSig   = 16    # TSIG Signature Failure                      [RFC2845]
    BadKey   = 17    # Key not recognized                          [RFC2845]
    BadTime  = 18    # Signature out of time window                [RFC2845]
    BadMode  = 19    # Bad TKEY Mode                               [RFC2930]
    BadName  = 20    # Duplicate key name                          [RFC2930]
    BadAlg   = 21    # Algorithm not supported                     [RFC2930]
    BadTrunc = 22    # Bad Truncation                              [RFC4635]
}