New-Enum -ModuleBuilder $DnsResolverModuleBuilder -Name "Indented.DnsResolver.IanaAddressFamily" -Type "UInt16" -Members @{
  IPv4                   = 1;        # IP version 4
  IPv6                   = 2;        # IP version 6
  NSAP                   = 3;        # NSAP
  HDLC                   = 4;        # HDLC (8-bit multidrop)
  BBN                    = 5;        # BBN 1822
  "802"                  = 6;        # 802 (includes all 802 media plus Ethernet "canonical format")
  "E.163"                = 7;        # E.163
  "E.164"                = 8;        # E.164 (SMDS, Frame Relay, ATM)		
  "F.69"                 = 9;        # F.69 (Telex)
  "X.121"                = 10;       # X.121 (X.25, Frame Relay)
  IPX                    = 11;       # IPX
  Appletalk              = 12;       # Appletalk
  DecNetIV               = 13;       # DecNet IV
  BanyanVines            = 14;       # Banyan Vines
  "E.164NSAP"            = 15;       # E.164 with NSAP format subaddress         [ATM Forum UNI 3.1. October 1995.][Andy_Malis]
  DNS                    = 16;       # DNS (Domain Name System)
  DistinguishedName      = 17;       # Distinguished Name                        [Charles_Lynn]	
  ASNumber               = 18;       # AS Number                                 [Charles_Lynn]
  XTPOverIpv4            = 19;       # XTP over IP version 4                     [Mike_Saul]
  XTPOverIPv6            = 20;       # XTP over IP version 6                     [Mike_Saul]
  XTPNativeMode          = 21;       # XTP native mode XTP                       [Mike_Saul]
  FibreChannelWWPortName = 22;       # Fibre Channel World-Wide Port Name        [Mark_Bakke]
  FibreChannelWWNodeName = 23;       # Fibre Channel World-Wide Node Name        [Mark_Bakke]
  GWID                   = 24;       # GWID                                      [Subra_Hegde]
  AFIForL2VPN            = 25;       # AFI for L2VPN information                 [RFC4761][RFC6074]
  MPLSTPSectionID        = 26;       # MPLS-TP Section Endpoint Identifier       [RFC-ietf-mpls-gach-adv-08]
  MPLSTPLSPID            = 27;       # MPLS-TP LSP Endpoint Identifier           [RFC-ietf-mpls-gach-adv-08]
  MPLSTPPseudowireID     = 28;       # MPLS-TP Pseudowire Endpoint Identifier    [RFC-ietf-mpls-gach-adv-08]
  EIGRPCommon            = 16384;    # EIGRP Common Service Family               [Donnie_Savage]
  EIGRPIPv4              = 16385;    # EIGRP IPv4 Service Family                 [Donnie_Savage]
  EIGRPIPv6              = 16386;    # EIGRP IPv6 Service Family                 [Donnie_Savage]
  LCAF                   = 16387;    # LISP Canonical Address Format (LCAF)      [David_Meyer]
  BGPLS                  = 16388;    # BGP-LS                                    [draft-ietf-idr-ls-distribution]
  MAC48bit               = 16389;    # 48-bit MAC                                [RFC-eastlake-rfc5342bis-05]
  MAC64bit               = 16390;    # 64-bit MAC                                [RFC-eastlake-rfc5342bis-05]
  OUI                    = 16391;    # OUI                                       [draft-eastlake-trill-ia-appsubtlv]
  MAC24                  = 16392;    # MAC/24                                    [draft-eastlake-trill-ia-appsubtlv]
  MAC40                  = 16393;    # MAC/40                                    [draft-eastlake-trill-ia-appsubtlv]
  "IPv6-64"              = 16394;    # IPv6/64                                   [draft-eastlake-trill-ia-appsubtlv]
  RBridgePortID          = 16395;    # RBridge Port ID                           [draft-eastlake-trill-ia-appsubtlv]
}

